machine_annotation_prompt: |-
  아래 목록은 번역투의 일반적인 유형을 분류한 거야.
  목록: -ㄴ 것, 진행형, 복수, 되다, 가지다, -에 의하다(by), 무생물주어, 대명사, -을 통해(through), -게 되다, -부터(from), -적, , 그리고, -어 지다, 완료형, , 또는, ㄹ 수
  수행 업무:
  위의 유형을 바탕으로 번역투를 탐지하고, 탐지한 번역투는 [ ] 를 이용해서 표시해.
  애매한 경우에는 가장 가까운 유형으로 분류하고, 이유를 써 놔.
  여러 유형이 겹칠 경우 가장 가까운 유형으로 분류해.
  원하는 결과 형식:
  {{번역투가 [ ]로 표시된 글}}
  수행 업무 예시:
  원문: 그사람으로부터 생긴 문제들을 최면을 통해 해결하는 것은 그들의 생각이었다. 그 해결법은 문제들을 해결하지 않고 있다. 지속적인 문제가 발생될 때, 그리고 그것을 막을 수 없을 때 그것을 통해 오는 절망은 해결할 수 없는 것으로 보여진다. 그래서 우리들은 문제에 대해 고민해왔고, 또는 도망쳐왔다. 따라서 우리는 운명에 의해 좌지우지 되어 지는 양상을 가지며, 운명에 의해 절망하게 된다.
  결과:
  [그] 사람[으로부터] 생긴 [문제들]을 최면[을 통해] 해결하[는 것은] [그들]의 생각이었다. [그] 해결법은 [문제들]을 해결하지 않[고 있다]. 지속[적]인 문제가 발생[될] 때[, 그리고] [그것]을 막을 수 없을 때 [그것]을 [통해] 오는 절망은 해결[할 수] 없[는 것]으로 보[여진다]. 그래서 [우리들]은 문제에 대해 고민[해왔고] [, 또는] 도망[쳐왔다.] 따라서 우리는 운명[에 의해] 좌지우지 되[어 지는] 양상을 [가지며], 운명[에 의해] 절망하[게 된다].
  결과 형식을 따르고 설명을 추가하지마.
  수행할 원문: 
  ${model_input}